import esbuild from "esbuild";
import process from "node:process";

const production = process.argv[2] === "production";
const context = await esbuild.context({
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: ["obsidian", "electron", "http"],
	format: "cjs",
	target: "es2021",
	outfile: "main.js",
	sourcemap: production ? false : "inline",
	minify: production,
	treeShaking: true,
	banner: { js: "/* Generated by esbuild. Source is available in this repository. */" },
});

if (production) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
